### ISSUE TITLE
FileNotFoundError,WebDriverException

### ISSUE THREAD

**Issue by giuseppe-coco** [mrgretwon/fut_sniping_bot#11]
there are these errors that I cannot correct
i downloaded selenium, i put the cromeDriver path in the PATH environment variable but still it doesn't run
why?
**Traceback (most recent call last):
  File "C:\Users\giuseppe\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\giuseppe\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\giuseppe\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\giuseppe\Desktop\fut_sniping_bot\src\main.py", line 4, in <module>
    bot = Bot()
  File "C:\Users\giuseppe\Desktop\fut_sniping_bot\src\bot.py", line 17, in __init__
    self.driver = create_driver()
  File "C:\Users\giuseppe\Desktop\fut_sniping_bot\src\config.py", line 18, in create_driver
    driver = webdriver.Chrome(
  File "C:\Users\giuseppe\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\giuseppe\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home**

**Comment by yahyatahir1** [comment]
I am also getting this issue? Any ideas mate?
